In [1]:
from transformers import BertModel, BertConfig

configuration = BertConfig()

model = BertModel(configuration)

configuration = model.config

In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('./jigsaw-toxic-comment-classification-challenge/train.csv')
data2 = pd.read_csv('./jigsaw-unintended-bias-in-toxicity-classification/train.csv')
data3 = pd.read_csv('./ruddit_with_text.csv')

In [7]:
data.head(5)
#data consists of [0, 1]

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

## Data2 description
target >= 0.5 (toxic)

target < 0.5 (non-toxic)

In [12]:
data2.head(5)

,id,target,comment_text,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
0,59848,0.000000,"This is so cool. It's like, 'would you want yo...",0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
1,59849,0.000000,Thank you!! This would make my life a lot less...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
2,59852,0.000000,This is such an urgent design problem; kudos t...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
3,59855,0.000000,Is this something I'll be able to install on m...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
4,59856,0.893617,haha you guys are a bunch of losers.,0.021277,0.0,0.021277,0.87234,0.0,0.0,0.0,...,2006,rejected,0,0,0,1,0,0.0,4,47

In [21]:
data2 = data2.fillna(0)

In [23]:
data2.toxicity_annotator_count.unique()

array([   4,   47,  105,   59,   75,   10,    6,   80,   65,   72,    5,
         71,    9,   32,   66,   55,   60,   11,   70,    7,   81,   68,
         69, 1128, 1166, 1070, 1062,   53,   76,   62,   56,    8,   58,
         48,   49, 1630,   74,   64,   67,   61, 1114,   52,   46, 1506,
         54, 1680,   63, 1379,   77,   73,  119, 1058, 1066,   44, 1604,
       1127,   40,   51, 1217, 1167,   57,   50, 1111, 1075, 1806, 1651,
         78,   45, 1867,   33,   43, 1512,   42, 1375, 1144,   12, 1728,
         39, 1855,   37,   34,  152,   98, 1652,   79, 1415,   38, 1380,
         36, 1143,   41, 1674,    3, 1736, 1093, 1573, 1108, 1668, 1205,
       1500, 3509,  218, 1665,  125, 1142, 1421, 1436,   82,  132,   35,
       1150, 1377, 1384,  110, 2915, 1397, 1079, 1208, 1119, 1764, 1201,
       1071, 1540, 1209, 1648, 1156, 1422, 1151, 1431, 1232, 1388, 1179,
       1876, 1086, 1148, 1059, 1868, 1758, 1672, 1189, 1481, 1057, 1184,
        194, 1367, 1064, 1643, 1088, 1503, 1616, 1743, 1132, 1686,  113,
       1344, 1087, 1092, 1545, 1502, 1833, 1487, 1225, 1395, 1669, 1207,
       1813, 1498,   93, 1850, 1497, 1135, 1399, 1181, 1223, 1513, 1844,
       1644, 1662, 1878, 1492, 1676, 1408,  181, 1790, 1180,   31, 1663,
       1198, 1394,   13, 1065, 1182, 1149, 1400, 1700, 1505, 1163, 1660,
       1804, 1107, 1398, 1549, 1731, 1897,  214, 1129, 1185, 1653, 1858,
       1106, 1460, 1162,  112, 1607, 1383, 1834, 1613, 1176, 1392, 1541,
       1202, 1811, 1777, 1857,   29, 1709, 1634, 3099, 1235, 1121, 1429,
       2748, 1495, 2467, 1617, 1035, 1510, 1440, 1362, 1647, 3338, 1216,
       1493, 1465,  124, 1624,  225, 1659, 1667, 1694, 1190, 1688, 1486,
       1414,  199, 1152,   94, 2820, 1363, 1744, 1658, 1859, 1847, 1751,
       1474, 1725, 1228, 1681, 1707,   28, 1334, 1679, 1735, 1558, 1871,
        104, 1354, 1685, 1705, 1348, 1122, 3071, 1602, 1699, 1213, 1434,
       1192, 1633, 1154, 1437,   30, 1165, 1720, 1390, 1749, 1445, 3316,
       1134, 1259, 1785, 1501, 1631, 1874, 3456, 1416, 1820,  127, 1830,
        342, 1230, 1726, 1649,  184, 1797, 1430, 1337, 1821, 1697, 1695,
       1601, 1824,  179, 1159, 1359, 1827, 1788, 1147, 1687, 1488, 1485,
       1200, 3383, 1862, 1420, 1670, 1374, 1369, 1760, 1657, 1547, 1732,
       1783, 1347, 1568, 1146, 1141, 1317,  107, 1067, 1654, 1233, 1425,
        210, 1391, 1378, 1714, 1881, 1831, 1560, 1801, 1825, 1446, 3287,
       1597, 1752, 1525, 1723, 1875,  213, 1641,  117, 1706, 1623, 1696,
       1650, 1671, 1471, 1161, 1155,  193, 1222, 1169, 1733, 1160,  168,
       1727, 1664, 1677, 1226,  143, 1153, 1593, 1439, 1776,   95, 1737,
        203, 1372, 1360, 1691, 1343, 1802, 1582, 1382, 1864, 1796, 1910,
       1453,  126,   99, 1234, 1428, 1424, 1885, 1559, 1358, 1853, 1592,
       1546, 1210, 1475, 1710, 1499,  122, 1328, 1750, 1585, 1352, 1215,
        229, 1851, 1410, 1621, 1852, 1386, 1839, 1583, 1600, 1158, 1353,
       1803, 1689, 1598, 1805, 1376, 1099, 1645, 1406, 1387, 3175, 1721,
       1814, 1433, 1522, 1381, 1124, 1404, 1741,   26, 1526, 1622,  196,
       1635, 1701, 1368,  377,  187,  188, 1690,  177,  256, 1224, 1432,
       3160, 1828,  123, 1884, 1757, 1504, 1638,  103, 1577, 4936, 1187,
       1365,  116, 1346, 1716, 1364, 1131, 1620,  211, 1618, 1683, 3068,
       1426, 1534, 1527, 1719, 1120, 1611, 1418, 1734, 1639, 1402, 1628,
       1661,  217, 1682, 1240, 1524, 1529, 1842, 1518, 1535, 1882, 1829,
       1196, 4177, 1449, 1873, 1355, 1666, 1508, 1104, 1417, 1393,  114,
       1837, 1678, 3043, 1389,  167, 1407, 1157, 1366, 3468, 1704, 1712,
         84, 1693, 2240, 3203, 1589, 1865, 4897,  109, 1468, 1838, 1818,
       1454, 1118,   83, 1564, 1880, 1703, 1412, 3305,  145, 1357, 1427,
       1555, 1462, 1646, 3623, 1791,  111,  102, 1117, 1490, 1371, 2087,
       1886, 1115,  128,   88, 1822,  172, 1327, 1029,  195, 1656, 1798,
       2168, 1779, 1539, 2133, 1715, 1356, 2167,  133,  974, 1110, 1123,
       3523, 1211, 1140, 1702, 1815, 1489, 1212, 1843, 1530, 1473, 1401,
       1171, 1137, 1684, 1136, 1848, 1514, 2116, 1077, 1385, 1450, 1073,
        274, 1591, 1708, 1405, 3091, 1409, 1178, 1470, 1606, 1713, 1800,
       1249,   14, 2911, 1020, 1866, 1629, 2129, 2176, 2150, 1587, 1755,
        205,  189, 2488, 2098,  100, 1444, 1840, 1243, 1784,  135, 1438,
        242, 1675, 1350, 2355, 1869, 1126,  220, 1849, 1841, 1879, 1632,
       1810, 1339, 1442, 1636, 2184, 1729, 2754, 2818, 1586, 2146,  150,
        120, 1570, 1193, 1612, 1051, 1016, 1692, 1063, 1625, 1373, 2804,
       2808, 1771, 3120, 1494, 2196, 1724, 3513, 1197, 1521, 1191, 2195,
       1175, 2189, 1550, 1261, 1411, 1455, 1074, 3137, 3141, 2598, 1342,
       1188, 1739,  157, 1452, 2900, 1186,  148, 1795, 1091, 1770, 1246,
       1203, 1845, 1458, 2160, 1717, 2127, 1786,  399, 1229, 2138, 1255,
       2118, 2186, 1516, 1044, 1482, 1722, 2158, 1856, 1138, 1170, 3163,
       1237, 1533, 1199,  176,  169, 1759,   97, 1435,  228, 1484, 1817,
       1610, 1103, 1528, 1095, 1013,  154, 1194, 1241, 2283,  992, 1507,
       1596, 1204, 1479, 1673, 2114, 2200, 1809, 1836, 1413,  131, 1747,
       1523,   24, 1711, 1164, 1247])

In [19]:
data2.identity_attack.max()

1.0